name: iOS Production Build

on:
  workflow_dispatch: {}

jobs:
  build_ios:
    name: Build iOS App Store
    type: build
    environment: production
    params:
      platform: ios
      profile: ios-production
      message: iOS App Store build from EAS Workflow
